### ISSUE TITLE
New to MkDocs: no output from plugin

### ISSUE THREAD

**Issue by Cry-Luca** [athackst/mkdocs-simple-plugin#112]
I read the instructions multiple times, but I can't get my code to be parsed.
I have it placed as a subfolder of docs
```
mkdocs.yml
docs/
│   code/  
│   README.md
│   ...
```

mkdocs.yml is the bare minimum:
```yml
site_name: KDB
plugins:
  - simple: null
  - search: null
theme: readthedocs
extra_css:
  - css/extra.css
```

The only output from mkdocs is:

> INFO    -  mkdocs-simple-plugin: build_docs_dir: C:\Users\luca\AppData\Local\Temp\mkdocs_simple_KDB4qzegjlc

The `C:\Users\luca\AppData\Local\Temp\mkdocs_simple_KDB4qzegjlc\code`  folder contains a verbatim copy of the contents of the original. Is that the expected output?
