### ISSUE TITLE
Error when using files from root and from docs folder

### ISSUE THREAD

**Issue by dfl-aeb** [athackst/mkdocs-simple-plugin#615]
First thanks for your great plugin and all the work you put into it.

We're experiencing a problem when using files from the root dir like the `README.md` and files from the `docs` dir like `docs/test.md`.

Our folder structure looks like this:

```
├── README.md
├── CHANGELOG.md
├── docs
│   └── test.md
└── mkdocs.yml
```

The `mkdocs.yml` looks like this:

```yaml
edit_uri: edit/main

nav:
  - Home: README.md 
  - Changelog: CHANGELOG.md
  - Test: docs/test.md

plugins:
  - simple:
      folders: ["docs/**", "./CHANGELOG.md", "./README.md"]
      merge_docs_dir: false

```

We needed to set merge_docs_dir to false to be able to specify the test docs like this `docs/test.md` in the nav section. This was the only way we could get the edit_uri to work properly (if there is another way please let me know).

By setting merge_docs_dir to false the docs get rendered correctly and the edit_uri works as expected. The problem is now, that mkdocs prints out this info message during the build:

```
INFO    -  The following pages exist in the docs directory, but are not included in the "nav" configuration:
             - docs/test.md

```

~~- The plugin copies the README and the CHANGELOG additionaly into the docs dir, which is not necessary because it's already in the root dir.~~ (My bad, I had copied the README and CHANGELOG into the docs folder)
- I don't understand whys mkdocs thinks that the `docs/test.md` is not included in the nav section. It is included and it gets rendered correctly. I assume it has something to do with the docs_dir that the simple plugin is setting?!

This is a bit confusing for our users. Is there a way to fix this?
