### ISSUE TITLE
doesn't seem to respect build_dir setting

### ISSUE THREAD

**Issue by gwhitney** [athackst/mkdocs-simple-plugin#791]
To reproduce, copy/edit the examples/ok-mkdocs-docs-merge example so that the mkdocs-test.yml file looks like:
```
# This example shows how to merge a docs folder with other documentation.
site_name: ok-mkdocs-docs-merge
plugins:
  - simple:
      build_dir: buildit
```
then run `mkdocs build --config-file mkdocs-test.yml`. The first line of the output is
```
INFO    -  mkdocs-simple-plugin: build_dir: /tmp/mkdocs_simple_8onf2elf
```
but I would expect it to be `[...]/ok-mkdocs-docs-merge/buildit`. (Just tried this with mkdocs-simple-plugin v3.2.0.)
