### ISSUE TITLE
semiliterate destination using pattern with no matching group crashes

### ISSUE THREAD

**Issue by gwhitney** [athackst/mkdocs-simple-plugin#93]
If a `semiliterate` block is specified with a destination that does not depend on the `pattern` match and the `pattern` parameter does not have a matching group, mkdocs crashes. Such parameters can be legitimately useful, as in:
```
  semiliterate:
  - pattern: 'LICENSE'
    destination: 'LICENSE.md'
    start: 'TERMS'
```
or in general, this idiom can be used if necessary to rename a specific project file in the generated documentation site.
In any case, such parameter settings should not cause a crash. Full disclosure: I wrote this bug -- my apologies! I will post a pull request fixing it momentarily.
