### ISSUE TITLE
Including a replacement to strip leading # for line-comment docs in Python disrupts h1s in """-string docs

### ISSUE THREAD

**Issue by gwhitney** [athackst/mkdocs-simple-plugin#96]
I'm filing this as followup to the comment in the discussion in #94 about hacking around this sort of dilemma with a ===-style heading.

I am happy to volunteer some effort to iron this wrinkle out. But of course we'd need an agreeable mechanism to solve the underlying difficulty.

The difficulty appears to stem from trying to support both styles of documentation blocks in .py files simultaneously.

The first possible mechanism that comes to mind is to allow multiple different 'start' regexps, and then the one that matches determines what 'stop' and 'replace' regexps are used (with 'terminate' presumably being universal). Is that appealing? If so, then we'd need a comfortable syntax for specifying such a thing.
One option:
```
  semiliterate:
  - pattern: '\.py$'
    extraction:
    - start: '"""\smd'
      stop: '"""'
    - start: '#\smd'
      stop: '#\s/md'
      replace: ['^\s*#\s(.*\n?)$']
  - pattern: '\.(js|etc,etc)$'
    extraction:
    - start: '/\*\*\smd'
      stop: '\*\*/'
```

The second possible mechanism that comes to mind is to allow match groups of the `start` match to come into play in the `replace` regexps:
```
   semiliterate:
   - pattern: '\.py$'
     start: '^((\s*)"""\s|(\s*# ))md'
     replace: ['^\g<2>\g<3>(.*\n?)$']
     end: '^\s*("""|# /md)'
```
This would work because group 2 in the start match is any whitespace before """ if that's what matches and the empty string otherwise, and group 3 in the start match is any whitespace before the `#`, the `#` itself, and one space, if that's what matches, and the empty string otherwise. So the concatenation of them, which is what `\g<2>\g<3>` would expand to, is precisely the prefix that you would want to strip from all lines of the block up to the end trigger.

The second proposal is more intricate but briefer and has no effect on typical patterns that only have one set of start and end markers. The first proposal is easier on the eyes and mind but more verbose for all patterns, including ones that are not using the extra power.

You may have other ideas you'd like me to implement, or you may prefer to handle this yourself. All fine with me, just offering to help (particularly given my role in getting you into this mess. ;-)
